apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-gke-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-gke-cd
  template:
    metadata:
      labels:
        app: github-gke-cd
    spec:
      containers:
        - name: app
          image: shreyaknoldus/github-actions-implementation-docker-image:latest
          imagePullPolicy: Always