apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-gke-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-gke-cd
  template:
    metadata:
      labels:
        app: github-gke-cd
    spec:
      containers:
        - name: app
          image: gcr.io/PROJECT_ID/IMAGE:TAG
          imagePullPolicy: Always